services:
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8932:5432"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://django_user:django_pass@db:5432/django_db
      PYTHONUNBUFFERED: 1
    restart: unless-stopped

volumes:
  postgres_data: